### ISSUE TITLE
如果能有动画就好些，看不到交互效果

### ISSUE THREAD

**Issue by wishcn** [hansenwangvip/right-button-ninja#3]
另外的就是开机启动最好也可以加一个

**Comment by hansenwangvip** [comment]
抱歉现在才看到issue，感谢建议，回复如下：
- 右键忍者和其他手势软件不同，没有鼠标指针的轨迹，因为初衷是为了让鼠标模拟触摸板。而大多数Windows笔记本的触摸板的交互是没有动画效果的。关于这个功能我会考虑在后期的GUI配置化上添加可选项。
- 开机启动目前只能通过手动添加，具体步骤如下：
1. 按快捷键：WIN + R；
2. 输入shell:startup，按回车；
3. 弹出了一个文件夹窗口；
4. 然后将RBN的exe文件复制进去，下次开机即可自启动；
5. 如果要关闭自启动，只需按照同样的步骤删除该文件即可。

**Comment by wishcn** [comment]
谢谢！
